openapi: "3.0.0"
info:
  title: "Wallet System"
  description: |
    This API provides endpoints for managing expenses within the Wallet System platform. 
    It allows users to create, retrieve expense records.
  version: "1.0.0"
tags:
  - name: Expenses
    description: Endpoints related to managing expenses within the platform.
    externalDocs:
      description: Learn more about Expenses
      url: http://dummywebsite.io/docs/expenses
servers:
 - url: './'
paths:
  /Expenses/Create:
    post:
      summary: Create an expense
      description: Creates a new expense record.
      tags:
        - Expenses
      operationId: createExpense
      requestBody:
        description: JSON request body for creating an expense.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExpenseRequestJson'
      responses:
        '200':
          description: The expense was created successfully
        '404':
          description: No user has been found.
          content:
            application/json:
              schema:
                anyOf:
                  - description: UserNotFound - The user for expence has not been found.
                    allOf:
                      - $ref: "#/components/schemas/ProblemDetails"
              examples:
                UserNotFound:
                  value:
                    type: https://tools.ietf.org/html/rfc7231#section-6.5.4
                    title: UserNotFound
                    status: 404
                    detail: No user has been found with the specified 'xxx' identifier.
        '422':
          description: This error is for business validation errors.
          content:
            application/json:
              schema:
                anyOf:
                  - description: Unprocessable Entity.
                    allOf:
                      - $ref: "#/components/schemas/ProblemDetails"
              examples:
                CurrencyMissMatch:
                  value:
                    type: https://datatracker.ietf.org/doc/html/rfc4918#section-11.2
                    title: CurrencyMissMatch
                    status: 404
                    detail: 'Expense creation failed: The user currency and the expense currency are different.'
  /Expenses/search:
    get:
       summary: Search expenses
       description: Retrieves a list of expenses based on provided search criteria.
       tags:
        - Expenses
       operationId: searchExpenses
       parameters:
         - name: userId
           in: query
           schema:
             type: integer
           description: The ID of the user whose expenses are to be retrieved.
         - name: sortBy
           in: query
           description: The field by which expenses should be sorted (e.g., "amount", "date").
           required: false
           explode: true
           schema:
             type: string
             default: amount
             enum:
               - amount
               - date
         - name: sortOption
           in: query
           description: The sorting order for expenses (either "ASC" for ascending or "DESC" for descending).
           required: false
           explode: true
           schema:
             type: string
             default: asc
             enum:
               - asc
               - desc
       responses:
         '200':
           description: Successful operation
           content:
             application/json:
               schema:
                 type: array
                 items:
                   $ref: "#/components/schemas/SearchExpenseResponseResult"

components:
  schemas:
    ProblemDetails:
      description: Represents an error message returned by the API using the format specified in the [RFC7807](https://tools.ietf.org/html/rfc7807).
      required:
        - type
        - title
        - status
        - detail
      properties:
        type:
          description: A URI reference [RFC3986](https://tools.ietf.org/html/rfc3986) that identifies the problem type
          type: string
          format: uri
          example: https://tools.ietf.org/html/rfc7231#section-6.5.1
        title:
          description: A short, human-readable summary of the problem type.
          type: string
          example: UserNotFound
        status:
          description: The HTTP status code [([RFC7231], Section 6)](https://tools.ietf.org/html/rfc7231#section-6) generated by the origin server for this occurrence of the problem.
          type: number
          format: int32
          example: 400
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: No user has been found with the specified 'xxx' identifier.
    CreateExpenseRequestJson:
      required:
       - amount
       - currencyCode
       - date
       - description
       - userId
       - expenseType
      type: object
      properties:
        amount:
          type: number
          description: The amount of the expense.
        currencyCode:
          type: string
          description: The currency code of the expense (ISO 4217).
          example: USD
          enum:
              - USD
              - RUB
        date:
          type: string
          format: date
          description: The date of the expense (ISO 8601).
        description:
          type: string
          description: A brief description of the expense.
        userId:
          type: integer
          description: The ID of the user associated with the expense.
        expenseType:
          type: string
          description: The type of the expense.
          example: Restaurant
          enum:
              - Restaurant
              - Hotel
              - Misc
    SearchExpenseResponseResult:
      type: object
      properties:
        amountValue:
          type: number
          description: The value of the expense amount
        amountCurrency:
          type: string
          description: The currency of the expense amount
        date:
          type: string
          format: date-time
          description: The date of the expense
        description:
          type: string
          description: Description of the expense
        type:
          type: string
          description: Type of the expense
        userFullName:
          type: string
          description: Full name of the user who incurred the expense