name: .NET with SonarCloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          find . -type f -name "*.csproj" ! -path "*/Sql.Database/WalletSystem.Sql.Database.sqlproj" | xargs -I{} dotnet build --no-restore "{}"
      - name: Test
        run: |
          find . -type f -name "*.csproj" ! -path "*/Sql.Database/WalletSystem.Sql.Database.sqlproj" | xargs -I{} dotnet test --no-build --verbosity normal "{}"
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Specify the path to your Java 17 installation
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-17-jdk  # Install OpenJDK 17
          dotnet sonarscanner begin /k:"KsiProgramming_WalletSystem" /o:"ksiprogramming" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          find . -type f -name "*.csproj" ! -path "*/Sql.Database/WalletSystem.Sql.Database.sqlproj" | xargs -I{} dotnet build "{}"
          find . -type f -name "*.csproj" ! -path "*/Sql.Database/WalletSystem.Sql.Database.sqlproj" | xargs -I{} dotnet test --no-build --verbosity normal "{}"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
